# https://taskfile.dev

version: "3"

tasks:
  build:
    vars:
      FLAGS: -ldflags="-s -w" -trimpath
      BINARY: ecs-meta2env
    env:
      CGO_ENABLED: 0
      GOOS: linux
    cmds:
      - GOARCH=amd64 go build {{.FLAGS}} -o ./bin/{{.BINARY}}-linux-amd64 .
      - GOARCH=arm64 go build {{.FLAGS}} -o ./bin/{{.BINARY}}-linux-arm64 .
      - cd ./bin && sha256sum {{.BINARY}}-* > sha256sum.txt
    silent: true
